[package]
name = "rocketmap-entities"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.5"
chrono = { version = "0.4", features = ["serde"] }
geo = { version = "0.18", features = ["use-serde"] }
once_cell = "1.9"
pogo-gamemaster-entities = { git = "https://github.com/nappa85/pogo-gamemaster-entities.git" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["time"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["time", "macros"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
