[package]
name = "rocketmap-entities"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.5.0"
chrono = { version = "0.4.19", features = ["serde"] }
geo = { version = "0.22.1", features = ["use-serde"] }
once_cell = "1.10.0"
pogo-gamemaster-entities = { git = "https://github.com/nappa85/pogo-gamemaster-entities.git" }
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio = { version = "1.18.1", features = ["time"] }
tracing = "0.1.34"

[dev-dependencies]
tokio = { version = "1.18.1", features = ["time", "macros"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
